// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhnB1fqselJSnCaFSf91AOcf91CxgPK28',
    appId: '1:904434929719:web:7c73f95f49542485d82fb2',
    messagingSenderId: '904434929719',
    projectId: 'geminiapp-583ec',
    authDomain: 'geminiapp-583ec.firebaseapp.com',
    storageBucket: 'geminiapp-583ec.appspot.com',
    measurementId: 'G-SCJ92SSHEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjWNFVPWWbQzZnPqqAWSZmgQo81sYj4lU',
    appId: '1:904434929719:android:4ffd370868c705b2d82fb2',
    messagingSenderId: '904434929719',
    projectId: 'geminiapp-583ec',
    storageBucket: 'geminiapp-583ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASLy_DXNLoOXiAKOqvGfyQq6Oi2RrUyGU',
    appId: '1:904434929719:ios:a6b27df8f3c1295dd82fb2',
    messagingSenderId: '904434929719',
    projectId: 'geminiapp-583ec',
    storageBucket: 'geminiapp-583ec.appspot.com',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASLy_DXNLoOXiAKOqvGfyQq6Oi2RrUyGU',
    appId: '1:904434929719:ios:a6b27df8f3c1295dd82fb2',
    messagingSenderId: '904434929719',
    projectId: 'geminiapp-583ec',
    storageBucket: 'geminiapp-583ec.appspot.com',
    iosBundleId: 'com.example.geminiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhnB1fqselJSnCaFSf91AOcf91CxgPK28',
    appId: '1:904434929719:web:50c6b9cfb0740d5fd82fb2',
    messagingSenderId: '904434929719',
    projectId: 'geminiapp-583ec',
    authDomain: 'geminiapp-583ec.firebaseapp.com',
    storageBucket: 'geminiapp-583ec.appspot.com',
    measurementId: 'G-9VT3M98JVJ',
  );
}
